stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the application"
    - docker compose -f docker-compose.test.yaml -p ci-test build --no-cache
    - docker compose -f docker-compose.yaml -p ci-prod build --no-cache

test-job:
  stage: test
  script:
    - echo "Building the test environment"
    - echo "Running tests"
    - docker compose -f docker-compose.test.yaml -p ci-test up --abort-on-container-exit --remove-orphans

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - docker compose -f docker-compose.yaml -p ci-prod up -d --remove-orphans
