stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the application"
    - docker compose build

test-job:
  stage: test
  script:
    - echo "Building the test environment"
    - docker compose -f docker-compose.test.yaml -p ci-test build
    - echo "Running tests"
    - docker compose -f docker-compose.test.yaml -p ci-test up --abort-on-container-exit

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - docker compose up -d
    - echo "Application successfully deployed."
