services:
  eelisr-service1:
    build: service1
    volumes:
      - ./logs:/logs/
    ports: 
    - 4001:4001
    environment:
      SERVICE_2_ADDRESS: 10.0.1.2 
      SERVICE_2_PORT: 8000
      FILE_PATH: /logs/service1.log
      OWN_IP: 10.0.1.3
      OWN_PORT: 4001
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.3

  eelisr-service2:    
    build: service2
    volumes:
      - ./logs:/logs/ 
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      FILE_PATH: /logs/service2.log
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.2


networks:
  eelisr-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/16
          gateway: 10.0.1.1

