services:
  eelisr-mq-test:
    image: rabbitmq:3
    ports:
      - 5672
      - 15672
    networks:
      eelisr-network-test:
        ipv4_address: 10.1.2.2

  eelisr-service1-test:
    build: service1
    ports:
      - 4001
    environment:
      SERVICE_2_ADDRESS: 10.1.2.4
      SERVICE_2_PORT: 8000
      OWN_PORT: 4001
      MQ_ADDRESS: 10.1.2.2
      MQ_PORT: 5672
    depends_on:
      - eelisr-mq-test
    networks:
      eelisr-network-test:
        ipv4_address: 10.1.2.3

  eelisr-service2-test:
    build:
      context: ./service2
      args:
        - MQ_ADDRESS=10.1.2.2:8080
    ports:
      - 8000
    environment:
      PORT: 8000
      MQ_ADDRESS: 10.1.2.2
      MQ_PORT: 5672
    depends_on:
      - eelisr-mq-test
      - eelisr-service1-test
    networks:
      eelisr-network-test:
        ipv4_address: 10.1.2.4

  eelisr-monitor-test:
    build:
      context: ./monitor
      args:
        - MQ_ADDRESS=10.1.2.2:8080
    ports:
      - 8087
    environment:
      MQ_ADDRESS: 10.1.2.2
      MQ_PORT: 5672
    depends_on:
      - eelisr-mq-test
      - eelisr-service1-test
      - eelisr-service2-test
    networks:
      eelisr-network-test:
        ipv4_address: 10.1.2.5

  eelisr-api:
    build:
      context: ./api
      args:
        - SERVICE_1_ADDRESS = 10.1.2.3:4001
        - MQ_ADDRESS = 10.1.2.2:5672
    ports:
      - 8083:8083
    depends_on:
      - eelisr-mq-test
      - eelisr-service1-test
      - eelisr-service2-test
      - eelisr-monitor-test
    networks:
      eelisr-network-test:
        ipv4_address: 10.1.2.6

  eelisr-tests:
    build:
      context: ./tests
      args:
        - API_ADDRESS = 10.1.2.6:8083
    depends_on:
      - eelisr-mq-test
      - eelisr-service1-test
      - eelisr-service2-test
      - eelisr-monitor-test
    networks:
      eelisr-network-test:
        ipv4_address: 10.1.2.7

networks:
  eelisr-network-test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.2.0/16
          gateway: 10.1.2.1
