services:
  eelisr-mq:
    image: rabbitmq:3
    ports:
      - 8080
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.2

  eelisr-service1:
    build: service1
    ports: 
    - 4001
    environment:
      SERVICE_2_ADDRESS: 10.0.1.4 
      SERVICE_2_PORT: 8000
      OWN_PORT: 4001
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.3

  eelisr-service2:    
    build: service2
    ports:
      - 8000
    environment:
      PORT: 8000
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.4

  eelisr-monitor:
    build: monitor
    ports:
      - 8087:8087
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.5

networks:
  eelisr-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/16
          gateway: 10.0.1.1

