services:
  eelisr-mq:
    image: rabbitmq:3
    ports:
      - 8080:5672 
      - 4001:15672
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.2

  eelisr-service1:
    build: service1
    ports: 
    - 4001
    environment:
      SERVICE_2_ADDRESS: 10.0.1.4 
      SERVICE_2_PORT: 8000
      OWN_PORT: 4001
      MQ_ADDRESS: 10.0.1.2:5672
    depends_on: 
      - eelisr-mq
      - eelisr-service2
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.3

  eelisr-service2:    
    build: 
      context: ./service2 
      args:
        - MQ_ADDRESS=10.0.1.2:8080
    ports:
      - 8000
    environment:
      PORT: 8000
      MQ_ADDRESS: 10.0.1.2:5672
    depends_on: 
      - eelisr-mq
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.4

  eelisr-monitor:
    build: 
      context: ./monitor 
      args:
        - MQ_ADDRESS=10.0.1.2:8080
    ports:
      - 8087:8087
    environment:
      MQ_ADDRESS: 10.0.1.2:5672
    depends_on: 
      - eelisr-mq
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.5

networks:
  eelisr-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/16
          gateway: 10.0.1.1

