services:
  eelisr-mq:
    image: rabbitmq:3-management
    ports:
      - 5672
      - 15672
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.2

  eelisr-service1:
    build: service1
    ports:
      - 4001
    environment:
      SERVICE_2_ADDRESS: 10.0.1.4
      SERVICE_2_PORT: 8000
      OWN_PORT: 4001
      MQ_ADDRESS: 10.0.1.2
      MQ_PORT: 5672
      ASPNETCORE_URLS: http://*:4001
    depends_on:
      - eelisr-mq
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.3

  eelisr-service2:
    build:
      context: ./service2
    ports:
      - 8000
    environment:
      PORT: 8000
      MQ_ADDRESS: 10.0.1.2
      MQ_PORT: 5672
    depends_on:
      - eelisr-mq
      - eelisr-service1
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.4

  eelisr-monitor:
    build:
      context: ./monitor
    ports:
      - 8087
    environment:
      MQ_ADDRESS: 10.0.1.2
      MQ_PORT: 5672
    depends_on:
      - eelisr-mq
      - eelisr-service1
      - eelisr-service2
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.5

  eelisr-api:
    build:
      context: ./api
    environment:
      SERVICE_1_ADDRESS: 10.0.1.3:4001
      SERVICE_2_ADDRESS: 10.0.1.4:8000
      MONITOR_ADDRESS: 10.0.1.5:8087
      MQ_ADDRESS: 10.0.1.2:5672
      MQ_MONITOR_ADDRESS: 10.0.1.2:15672
      PORT: 8083
    ports:
      - 8083:8083
    depends_on:
      - eelisr-service1
      - eelisr-service2
      - eelisr-monitor
    networks:
      eelisr-network:
        ipv4_address: 10.0.1.6

networks:
  eelisr-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/16
          gateway: 10.0.1.1
